process.env.MANAGER_URL = 'http://localhost:3001'
process.env.REDIS_HOST = 'dummy'
process.env.REDIS_KEY_PREFIX = 'forms-designer'
process.env.REDIS_PASSWORD = 'dummy'
process.env.REDIS_USERNAME = 'dummy'
process.env.SESSION_COOKIE_PASSWORD = 'test-env-session-cookie-password'
process.env.NOTIFY_TEMPLATE_ID = 'dummy'
process.env.NOTIFY_API_KEY = 'dummy'
process.env.DESIGNER_URL = 'https://forms-designer'
process.env.SUBMISSION_URL = 'https://test-submission-api.cdp-int.defra.cloud'
process.env.UPLOADER_URL = 'https://test-uploader.cdp-int.defra.cloud'
process.env.UPLOADER_BUCKET_NAME = 'dummy-bucket'
process.env.GOOGLE_TAG_MANAGER_CONTAINER_ID = 'GTM-XXXXXXXX'
process.env.GOOGLE_ANALYTICS_CONTAINER_ID = 'YYYYYYYYYY'
process.env.BASE_URL = 'http://localhost:3009'
process.env.SNS_ADAPTER_TOPIC_ARN =
  'arn:aws:sns:eu-west-2:123456789012:test-adapter-topic'
process.env.SNS_SAVE_TOPIC_ARN =
  'arn:aws:sns:eu-west-2:123456789012:test-save-topic'
process.env.SNS_ADAPTER_TOPIC_ARN =
  'arn:aws:sns:eu-west-2:123456789012:test-adapter-topic'
process.env.SNS_ENDPOINT = 'http://localhost:4566'
process.env.PRIVATE_KEY_FOR_SECRETS = 'dummy-private-key'
process.env.SNS_FORM_TOPIC_ARN_MAP =
  '{"507f1f77bcf86cd799439099":"arn:aws:sns:eu-west-2:123456789012:form-specific-topic"}'
