process.env.REDIS_HOST = 'dummy'
process.env.REDIS_KEY_PREFIX = 'forms-designer'
process.env.REDIS_PASSWORD = 'dummy'
process.env.REDIS_USERNAME = 'dummy'
process.env.SESSION_COOKIE_PASSWORD = 'test-env-session-cookie-password'
process.env.NOTIFY_TEMPLATE_ID = 'dummy'
process.env.NOTIFY_API_KEY = 'dummy'
