export { default as authRoutes } from '~/src/server/routes/auth.js'
export { default as homepageRoutes } from '~/src/server/routes/homepage.js'
export { default as publicRoutes } from '~/src/server/routes/public.js'
export { default as healthRoute } from '~/src/server/routes/health.js'
export { default as saveAndExitRoutes } from '~/src/server/routes/save-and-exit.js'
export { default as saveAndExitV2Routes } from '~/src/server/routes/save-and-exit-v2.js'
