name: Publish

on:
  push:
    branches:
      - main

    paths:
      - '.browserslistrc'
      - 'babel.config.*'
      - 'postcss.config.*'
      - 'webpack.config.*'
      - 'Dockerfile'
      - 'src/**'
      - '!**/*.test.*'

  workflow_dispatch:
    inputs:
      version:
        description: Version number (optional)
        required: false

concurrency:
  group: publish

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-workflow
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Publish
        uses: DEFRA/cdp-build-action/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}
